- name: "Desenvolvimento Web"
  icon: "code"
  description: "Seu site desenvolvido com algumas das mais confiáveis linguagens atuais. PHP7, MySQL, Bootstrap 4, CSS 3."

- name: "Wordpress"
  icon: "wordpress"
  description: "Desenvolvimento e configuração de sites na plataforma Wordpress. Escolha de tema condizente com o da empresa, passando pela configuração, até a hospedagem."

- name: "Designer Gráfico"
  icon: "laptop"
  description: "Atuo como Designer Gráfico, produzindo material para mídias impressas e virtuais."
